name: Publish site (safe first run)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Generate articles
        run: python scripts/generate_article.py --count 5
      - name: Rebuild index & feeds
        run: |
          python scripts/build_index.py
          python scripts/generate_sitemap.py
          python scripts/generate_rss.py
      - name: Commit & push changes
        run: |
          git config user.name "auto-publisher"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git commit -m "auto: publish $(date -u +'%Y-%m-%d %H:%M:%S')" || echo "No changes"
          git push
